apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
data:
  myvalue: "Hello chart1"
  {{- with .Values.favourite }}
  drink: {{  .drink |  quote }}
  food: {{  .food | upper | quote  }}
  {{- if eq .drink "coffee" }}
  cup: true
  {{- end }}
  preference: {{ print "I prefer  " .drink " to juice" }}
  {{- end }}