apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
data:
  myvalue: "Hello chart1"

  {{- $relname:= .Release.Name -}}

  {{- with .Values.favourite }}
  drink: {{  .drink |  quote }}
  food: {{  .food | upper | quote  }}

  {{- if eq .drink "coffee" }}
  cup: true
  {{- end }}

  preference: {{ print "I prefer  " .drink  " to juice" }}
  release: {{ $relname }}
  {{- end }}

  toppings: |-
    {{- range $index, $topping := .Values.pizzaToppings }}
    - {{ $index }} : {{ $topping }}
    {{- end }}

