
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
  {{- template "mychart.labels" }}   #_helpers.tpl a define kora label akhane template dia use kora hocche

data:
  myvalue: "Hello chart1"


  {{- $relname:= .Release.Name -}} #assign variable

  {{- with .Values.favourite }}  # with scope
  drink: {{  .drink |  quote }}
  food: {{  .food | upper | quote  }}

  {{- if eq .drink "coffee" }}  # if
  cup: true
  {{- end }}

  preference: {{ print "I prefer  " .drink  " to juice" }} #print function
  release: {{ $.Release.Name }} # usause of dollar sign
  {{- end }}

  toppings: |- #for loop
    {{- range $index, $topping := .Values.pizzaToppings }}
    - {{ $index }} : {{ $topping }}
    {{- end }}

