
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
  labels: {{ include "chart1.app" . | indent 4}}   #_helpers.tpl a define kora label akhane template dia use kora hocche

data:
  myvalue: "Hello chart1"


  {{- $relname:= .Release.Name -}} #assign variable

  {{- with .Values.favourite }}  # start with scope
  drink: {{  .drink |  quote }}
  food: {{  .food | upper | quote  }}

  {{- if eq .drink "coffee" }}  # if
  cup: true
  {{- end }}

  preference: {{ print "I prefer  " .drink  " to juice" }} #print function
  release: {{ $.Release.Name }} # use of dollar sign
  {{- end }} #end of with scope

  #for loop
  toppings: |-
    {{- range $index, $topping := .Values.pizzaToppings }}
    - {{ $index }} : {{ $topping }}
    {{- end }}
  {{ include "chart1.app" . | indent 2}}

  #file
  {{- $files := .Files }}
  {{- range tuple "config1.toml" "config2.toml" "config3.toml" }}
  {{ . }}: |-
    {{ $files.Get . }}
  {{- end }}

