apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
data:
  myvalue: "Hello chart1"
  {{- with .Values }}
  drink: {{  .favourite.drink |  quote }}
  food: {{  .favourite.food | upper | quote  }}
  {{- if eq .favourite.drink "coffee" }}
  cup: true
  {{- end }}
  preference: {{ print "I prefer  " .favourite.drink " to juice" }}
  {{- end }}